// Generate both CSS profiles from src/color.mjs. Commit the results: git installs
// this package without running lifecycle scripts.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { getPalette, PALETTE_IDS } from "../src/color.mjs";

const dir = fileURLToPath(new URL("../color/", import.meta.url));
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const value = (key, val) => `  --${kebab(key)}: ${val};`;

function block(id) {
  const p = getPalette(id);
  const lines = [`:root[data-orumio-palette="${id}"],`, `[data-orumio-palette="${id}"],`,
    `[data-orumio-palette="${id}"] [data-theme="${p.colorScheme}"] {`,
    `  color-scheme: ${p.colorScheme};`];
  for (const [key, val] of Object.entries(p.app)) lines.push(value(key, val));
  lines.push(value("mutedStrong", p.site.mutedStrong));
  lines.push(value("activeStrong", p.site.activeStrong));
  lines.push(value("attentionStrong", p.site.attentionStrong));
  lines.push("  --eclipse: var(--foreground);");
  lines.push("  --teal: var(--active);");
  for (const key of ["surface", "surface-secondary", "surface-tertiary", "overlay", "default", "field"]) {
    lines.push(`  --${key}-foreground: var(--foreground);`);
  }
  lines.push(`  --surface-selected: color-mix(in oklab, var(--foreground) ${id === "warm-neutral" ? "5%" : "10%"}, transparent);`);
  lines.push("  --tint-surface: 10%;", "  --tint-soft: 15%;", "  --tint-soft-hover: 22%;");
  for (const key of ["accent", "danger", "success", "warning", "active", "attention"]) {
    lines.push(`  --${key}-surface: color-mix(in oklab, var(--${key}) var(--tint-surface), var(--background));`);
    lines.push(`  --${key}-soft: color-mix(in oklab, var(--${key}) var(--tint-soft), var(--background));`);
    if (["accent", "danger"].includes(key)) lines.push(`  --${key}-soft-hover: color-mix(in oklab, var(--${key}) var(--tint-soft-hover), var(--background));`);
  }
  lines.push("  --active-soft-foreground: color-mix(in oklab, var(--active) 80%, var(--foreground) 30%);");
  lines.push("  --attention-soft-foreground: color-mix(in oklab, var(--attention) 80%, var(--foreground) 30%);");
  for (const key of ["danger", "success", "warning"]) {
    lines.push(`  --${key}-soft-foreground: color-mix(in oklab, var(--${key}) 80%, var(--foreground) 30%);`);
  }
  lines.push("  --default-soft: var(--surface-tertiary);");
  lines.push("}");
  return lines.join("\n");
}

const base = `/* GENERATED by scripts/gen-color.mjs from src/color.mjs — do not edit. */\n${PALETTE_IDS.map(block).join("\n\n")}\n`;
const site = `${base}\n@theme inline {\n${[
  "background", "foreground", "surface", "surface-secondary", "muted", "muted-strong",
  "border", "accent", "accent-foreground", "active", "active-soft", "attention",
  "attention-soft", "active-strong", "attention-strong",
].map((name) => `  --color-${name}: var(--${name});`).join("\n")}\n}\n`;
const outputs = [["app.css", base], ["site.css", site]];
if (!process.argv.includes("--check")) mkdirSync(dir, { recursive: true });
let drift = false;
for (const [name, content] of outputs) {
  const path = `${dir}${name}`;
  const old = (() => { try { return readFileSync(path, "utf8"); } catch { return null; } })();
  if (process.argv.includes("--check")) {
    if (old !== content) { console.error(`${name} is stale`); drift = true; }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
if (drift) process.exitCode = 1;
