#!/usr/bin/env node
// gen — compute shape/tokens.css, shape/roles.css and shape/circles.css from src/roles.mjs (the decision)
// and src/census.generated.json (the HeroUI rows it decides about).
//
//   node scripts/gen.mjs            write the three files
//   node scripts/gen.mjs --check    exit 1 if any of them differs from what would be written
//
// No network, no HeroUI: everything it needs is committed. Named gen, never build — a `build` script
// would run when the package is installed from git (SHAPE.md §Distribution).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const R = await import(pathToFileURL(path.join(root, "src/roles.mjs")).href);
const census = JSON.parse(fs.readFileSync(path.join(root, "src/census.generated.json"), "utf8"));

const HEADER = (what) =>
  `/* GENERATED by scripts/gen.mjs from src/roles.mjs and src/census.generated.json — do not edit.\n   ${what} */\n`;

// ── Classification ────────────────────────────────────────────────────────────────────────────────
const KEEPABLE = new Set(["ladder", "zero", "inherit", "field"]);
const STEP_NAMES = Object.keys(R.STEPS);
const ROLE_NAMES = Object.keys(R.ROLES);

function isClassified(row) {
  return row.pkg === "@heroui/styles" || R.PRO_CLASSIFIED.includes(row.component);
}

function matches(rule, row) {
  const [component, sel] = rule;
  if (component !== row.component) return false;
  if (sel === null) return true;
  if (sel instanceof RegExp) return sel.test(row.selector);
  return sel === row.selector;
}

/** → { role } where role ∈ ROLE_NAMES ∪ STEP_NAMES ∪ {circle, keep, inherit, skip}. Throws on a row of a
 *  classified component that no rule reaches, and on a keep that would carry a non-ladder value. */
export function decide(row) {
  if (row.kind === "zero" || row.kind === "field") return "keep";
  if (row.kind === "inherit") return "inherit";
  if (row.kind === "circle") return R.CIRCLE;
  if (!isClassified(row)) {
    // A Pro component no product imports: HeroUI's own step for N; a ladder / token variable stays.
    if (row.kind === "base") return row.autoStep;
    if (row.kind === "ladder" || row.kind === "component-var") return "keep";
    return "skip"; // a literal we may not publish and nobody renders — SHAPE.md §Unclassified Pro
  }
  const rule = R.RULES.find((r) => matches(r, row));
  if (!rule) throw new Error(`unclassified row: ${row.component} ${row.selector} ${row.prop} (${row.kind})`);
  const role = rule[2];
  if (role === "keep" && !KEEPABLE.has(row.kind))
    throw new Error(`keep on a ${row.kind} value: ${row.component} ${row.selector} — give it a role or a step`);
  if (![...ROLE_NAMES, ...STEP_NAMES, R.CIRCLE, "keep"].includes(role)) throw new Error(`unknown role ${role}`);
  return role;
}

/** The part a row's element is: its own BEM block or element (a `--modifier` dropped), else its
 *  data-slot, else the nearest such name to its left, else the component.
 *  `.tabs--secondary > .tabs__list-container .tabs__tab` → `tabs-tab`; `.sheet__content--bottom` →
 *  `sheet-content`. Parts are the names a product's deviation can address (`--shape-part-<part>`). */
export function partOf(row) {
  const subject = splitTop(row.selector).at(-1);
  const compounds = subject.split(/\s*[\s>+~]\s*(?![^(]*\))/).filter(Boolean);
  for (let i = compounds.length - 1; i >= 0; i--) {
    // :is() / :where() name the subject; :not() / :has() only filter it.
    const c = compounds[i].replace(/:(not|has)\((?:[^()]|\([^()]*\))*\)/g, "");
    const cls = [...c.matchAll(/\.([a-z0-9]+(?:-[a-z0-9]+)*(?:__[a-z0-9]+(?:-[a-z0-9]+)*)?)/g)].map((m) => m[1]);
    if (cls.length) return cls[0].replace("__", "-");
    const slot = c.match(/\[data-slot="?([a-z0-9-]+)"?\]/);
    if (slot) return slot[1];
  }
  return row.component;
}

function splitTop(list) {
  const out = [];
  let depth = 0;
  let cur = "";
  for (const ch of list) {
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (ch === "," && depth === 0) {
      out.push(cur.trim());
      cur = "";
    } else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

function valueFor(row, role) {
  if (ROLE_NAMES.includes(role)) return `var(--shape-part-${partOf(row)}, var(--radius-${role}))`;
  if (STEP_NAMES.includes(role)) return `var(--radius-${role})`;
  if (role === R.CIRCLE) return "9999px";
  if (role === "inherit") return "inherit";
  if (role === "keep") {
    if (row.value === undefined) throw new Error(`keep without a publishable value: ${row.selector}`);
    return row.value;
  }
  throw new Error(`no value for ${role}`);
}

// ── Emission ──────────────────────────────────────────────────────────────────────────────────────
/** Emit declarations grouped by context, then by rule path, preserving the census order — which is
 *  HeroUI's cascade order — so every re-emitted rule meets its neighbours in the order HeroUI wrote them. */
function emit(entries) {
  const blocks = [];
  for (const { row, decls } of entries) {
    const ctx = row.ctx ? row.ctx.split(" > ") : [];
    const ck = JSON.stringify(ctx);
    let block = blocks.at(-1);
    if (!block || block.ck !== ck) blocks.push((block = { ck, ctx, rules: [] }));
    const pk = JSON.stringify(row.path);
    let rule = block.rules.at(-1);
    if (!rule || rule.pk !== pk) block.rules.push((rule = { pk, path: row.path, decls: [] }));
    rule.decls.push(...decls);
  }
  const ind = (n) => "  ".repeat(n);
  let out = "";
  for (const b of blocks) {
    b.ctx.forEach((c, i) => (out += `${ind(i)}${c} {\n`));
    for (const r of b.rules) {
      const base = b.ctx.length;
      r.path.forEach((p, i) => (out += `${ind(base + i)}${p} {\n`));
      for (const d of r.decls) out += `${ind(base + r.path.length)}${d}\n`;
      for (let i = r.path.length - 1; i >= 0; i--) out += `${ind(base + i)}}\n`;
    }
    for (let i = b.ctx.length - 1; i >= 0; i--) out += `${ind(i)}}\n`;
  }
  return out;
}

// ── Corner shape follows the radius, corner by corner ─────────────────────────────────────────────
// A row that sets a radius also sets the SAME corners' shape, in the same rule: whatever wins a
// corner's radius (specificity, then order) then wins its shape too. Declaring the shape only on
// circle rows let a more specific non-circle row take the radius and leave the circle's `round`
// behind (the square colour swatches, found by the specimen). A custom property that carries a
// radius sets no shape on the element that DEFINES it; the rows that READ it take the shape.
const SHAPE_PROP = {
  "border-radius": "corner-shape",
  "border-top-left-radius": "corner-top-left-shape",
  "border-top-right-radius": "corner-top-right-shape",
  "border-bottom-right-radius": "corner-bottom-right-shape",
  "border-bottom-left-radius": "corner-bottom-left-shape",
  "border-start-start-radius": "corner-start-start-shape",
  "border-start-end-radius": "corner-start-end-shape",
  "border-end-start-radius": "corner-end-start-shape",
  "border-end-end-radius": "corner-end-end-shape",
};

/** Decisions for custom properties that carry a radius (`--resizable-indicator-radius: …`). */
const varRole = new Map();
for (const row of census.rows) if (row.prop.startsWith("--")) varRole.set(row.prop, decide(row));

/** The shape a row's corners take, or null for none (a custom property; a zero corner has no curve). */
export function shapeFor(row, role) {
  if (row.prop.startsWith("--")) return null;
  if (row.kind === "zero") return null;
  if (role === R.CIRCLE) return "round";
  if (role === "inherit") return "inherit";
  if (row.kind === "component-var") {
    const name = row.value?.match(/^var\((--[a-z0-9-]+)\)$/)?.[1];
    return varRole.get(name) === R.CIRCLE ? "round" : "var(--shape-curvature)";
  }
  return "var(--shape-curvature)";
}

function shapeDecl(row, role) {
  const shape = shapeFor(row, role);
  const prop = SHAPE_PROP[row.prop];
  return shape && prop ? [`${prop}: ${shape};`] : [];
}

function rolesCss() {
  const entries = [];
  for (const row of census.rows) {
    const role = decide(row);
    if (role === "skip") continue;
    entries.push({ row, decls: [`${row.prop}: ${valueFor(row, role)};`, ...shapeDecl(row, role)] });
  }
  const capped = R.HEIGHT_CAPPED.map(({ selector, height, role }) => {
    const part = selector.replace(/^\./, "").replace(/--.*$/, "").replace("__", "-");
    return `    ${selector} {\n      border-radius: min(var(--shape-part-${part}, var(--radius-${role})), calc(var(--shape-scale) * ${height} / 2));\n    }\n`;
  }).join("");
  return (
    HEADER(
      "Every HeroUI radius row the census found, re-emitted with the SAME selector (so the same specificity) in\n   HeroUI's own order, after HeroUI in the same layer: a role's variable wins, and HeroUI's state and\n   compound rules keep meeting each other exactly as HeroUI arranged them.",
    ) +
    emit(entries) +
    `\n/* A radius larger than half the element's height is clamped to it, so --shape-scale cannot shrink it.\n   Where the height is known, the fallback silhouette is set explicitly on an engine without the\n   curvature: the scaled half-height, the arc closest to the squircle pill Chromium draws. */\n@layer components {\n  @supports not (corner-shape: ${R.CURVATURE}) {\n${capped}  }\n}\n`
  );
}

function circlesCss() {
  const entries = [];
  for (const row of census.rows) {
    const role = decide(row);
    if (role === R.CIRCLE) entries.push({ row, decls: [`${row.prop}: 9999px;`, ...shapeDecl(row, role)] });
    else if (role === "inherit") entries.push({ row, decls: shapeDecl(row, role) });
    else if (shapeFor(row, role) === "round") entries.push({ row, decls: shapeDecl(row, role) }); // reads a circle variable
  }
  return (
    HEADER(
      "circle is a ROLE: a true circle (or pill) at 9999px with `corner-shape: round`, never the curvature.\n   An element that inherits its parent's radius inherits its corner shape too.",
    ) + emit(entries)
  );
}

function tokensCss() {
  const steps = Object.entries(R.STEPS);
  const roles = Object.entries(R.ROLES);
  return (
    HEADER("The ladder, the roles, and HeroUI's base. SHAPE.md §Tokens is the prose.") +
    `@theme static {\n` +
    steps.map(([s]) => `  --radius-${s}: calc(var(--shape-step-${s}) * var(--shape-scale));\n`).join("") +
    roles.map(([r]) => `  --radius-${r}: var(--shape-role-${r});\n`).join("") +
    `}\n\n@layer theme {\n  :root,\n  :host {\n    --shape-scale: 1;\n    --shape-curvature: ${R.CURVATURE};\n    --shape-base: ${R.BASE};\n` +
    steps.map(([s, v]) => `    --shape-step-${s}: ${v};\n`).join("") +
    roles.map(([r, s]) => `    --shape-role-${r}: var(--radius-${s});\n`).join("") +
    `  }\n}\n\n/* HeroUI defines these in its base layer on this selector list; the same list, later, wins. */\n@layer base {\n  :root,\n  .light,\n  .default,\n  [data-theme="light"],\n  [data-theme="default"] {\n    --radius: calc(var(--shape-base) * var(--shape-scale));\n    --field-radius: var(--shape-part-field, var(--radius-control));\n  }\n}\n`
  );
}

const files = {
  "shape/tokens.css": tokensCss(),
  "shape/roles.css": rolesCss(),
  "shape/circles.css": circlesCss(),
};

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const check = process.argv.includes("--check");
  let drift = 0;
  for (const [rel, content] of Object.entries(files)) {
    const file = path.join(root, rel);
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (current === content) continue;
    if (check) {
      console.error(`drift: ${rel}`);
      drift++;
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (drift) process.exit(1);
}
export { files };
